---
output: github_document
---
  
```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "figures/README-",
  out.width = "100%"
)
```

# Geocode benchmark

Analisando o efeito do número de threads e observações no tempo de
processamento.

```{r, echo = FALSE, warning = FALSE}
library(ggplot2)
library(targets)

old_server_timings <- readRDS(tar_read(old_server_timings_path))
old_server_timings[, server := "old"]

new_server_timings <- readRDS(tar_read(new_server_timings_path))
new_server_timings[, server := "new"]

third_server_timings <- readRDS(tar_read(third_server_timings_path))
third_server_timings[, server := "third"]

fourth_server_timings <- readRDS(tar_read(fourth_server_timings_path))
fourth_server_timings[, server := "fourth"]

timings <- rbind(old_server_timings, new_server_timings, third_server_timings, fourth_server_timings)

timings <- timings[
  ,
  .(avg_time = mean(time)),
  by = .(n_threads, n_rows, server)
]
timings[, expected_speedup := n_threads / n_threads[1], by = .(n_rows, server)]
timings[, actual_speedup := avg_time[1] / avg_time, by = .(n_rows, server)]

ggplot(timings) +
  geom_line(aes(x = n_threads, y = avg_time / 60, color = server, group = server)) +
  geom_point(aes(x = n_threads, y = avg_time / 60, color = server)) +
  scale_y_continuous(
    "Tempo de processamento (minutos)",
    labels = scales::label_number(),
    limits = c(0, 5)
  ) +
  scale_x_continuous(
    "Número de threads",
    labels = scales::label_number(),
    limits = c(10, 40)
  ) +
  scale_color_discrete("Servidor", labels = c("Novo", "Antigo", "Terceiro", "Quarto")) +
  ggtitle("Tempo de processamento por número de threads")

melted_timings <- data.table::melt(
  timings,
  id.vars = c("n_threads", "n_rows", "server"),
  measure.vars = c("expected_speedup", "actual_speedup"),
  variable.name = "type",
  value.name = "speedup"
)

ggplot(melted_timings) +
  geom_line(
    aes(
      x = n_threads,
      y = speedup,
      color = server,
      linetype = type,
      group = type
    )
  ) +
  geom_point(aes(x = n_threads, y = speedup, color = server)) +
  facet_wrap(
    ~ server,
    nrow = 1,
    labeller = as_labeller(c("new" = "Novo", "old" = "Antigo", "third" = "Terceiro", "fourth" = "Quarto"))
  ) +
  scale_y_continuous(
    "Speed-up (referência: tempo de processamento com 10 threads)",
    labels = scales::label_number(suffix = "x"),
    limits = c(1, 4)
  ) +
  scale_x_continuous(
    "Número de threads",
    labels = scales::label_number(),
    limits = c(10, 40)
  ) +
  scale_color_discrete("Servidor", labels = c("Novo", "Antigo")) +
  scale_linetype_discrete("Speed-up", labels = c("Esperado", "Realizado")) +
  ggtitle("Speed-up: esperado vs realizado")
```
